import { marketPagePaths } from "@/lib/design/market-page-paths";
import type { HomeWidget, MainSection, NavItem } from "./types";

export const SITE_NAME = "Pattaya.com";
export const SITE_TAGLINE = "Your trusted guide to Pattaya";

export const mainSections: MainSection[] = [
  {
    id: "news",
    label: "News",
    labelTh: "ข่าวสาร",
    description: "Pattaya news, expat updates, and local happenings",
    href: "/news",
    items: [
      {
        slug: "local-news/city-updates",
        label: "City Updates",
        labelTh: "ข่าวเมือง",
        description: "Latest updates from around Pattaya city",
        category: "Local News",
        subcategory: "City Updates",
        priority: "very-high",
        monetization: "Ads",
        features: "SEO",
        href: "/news/local-news/city-updates",
      },
      {
        slug: "local-news/crime",
        label: "Police & Crime",
        labelTh: "ตำรวจ อาชญากรรม",
        description: "Police reports and crime news in Pattaya",
        category: "Local News",
        subcategory: "Police & Crime",
        priority: "high",
        monetization: "Ads",
        href: "/news/local-news/crime",
      },
      {
        slug: "local-news/accidents",
        label: "Accidents",
        labelTh: "อุบัติเหตุ",
        description: "Real-time accident reports and traffic incidents",
        category: "Local News",
        subcategory: "Accidents",
        priority: "high",
        monetization: "Ads",
        features: "Real-time",
        href: "/news/local-news/accidents",
      },
      {
        slug: "local-news/infrastructure",
        label: "Roads & Utilities",
        labelTh: "ถนน ระบบเมือง",
        description: "Infrastructure, roads, and utility updates",
        category: "Local News",
        subcategory: "Roads & Utilities",
        priority: "medium",
        href: "/news/local-news/infrastructure",
      },
      {
        slug: "tourism/attractions",
        label: "Attractions",
        labelTh: "สถานที่เที่ยว",
        description: "Tourism news about Pattaya attractions",
        category: "Tourism News",
        subcategory: "Attractions",
        priority: "high",
        monetization: "Affiliate",
        href: "/news/tourism/attractions",
      },
      {
        slug: "tourism/promotions",
        label: "Promotions",
        labelTh: "โปรโรงแรม ร้านอาหาร",
        description: "Hotel and restaurant promotions in Pattaya",
        category: "Tourism News",
        subcategory: "Promotions",
        priority: "medium",
        monetization: "Affiliate",
        href: "/news/tourism/promotions",
      },
      {
        slug: "business/hotels",
        label: "Hotel Industry",
        labelTh: "โรงแรม",
        description: "Hotel industry news and developments",
        category: "Business News",
        subcategory: "Hotel Industry",
        priority: "high",
        monetization: "Ads",
        href: "/news/business/hotels",
      },
      {
        slug: "business/real-estate",
        label: "Property Market",
        labelTh: "อสังหา",
        description: "Real estate and property market updates",
        category: "Business News",
        subcategory: "Property Market",
        priority: "very-high",
        monetization: "Property Ads",
        href: "/news/business/real-estate",
      },
      {
        slug: "business/openings",
        label: "New Businesses",
        labelTh: "ร้านเปิดใหม่",
        description: "New business openings in Pattaya",
        category: "Business News",
        subcategory: "New Businesses",
        priority: "medium",
        monetization: "Sponsored",
        href: "/news/business/openings",
      },
      {
        slug: "expat/visa",
        label: "Visa News",
        labelTh: "วีซ่า",
        description: "Visa regulations and updates for expats",
        category: "Expat News",
        subcategory: "Visa News",
        priority: "very-high",
        monetization: "Visa Agents",
        features: "SEO",
        href: "/news/expat/visa",
      },
      {
        slug: "expat/immigration",
        label: "Immigration Updates",
        labelTh: "ข่าว ตม.",
        description: "Immigration office news and policy changes",
        category: "Expat News",
        subcategory: "Immigration Updates",
        priority: "very-high",
        monetization: "Visa Agents",
        href: "/news/expat/immigration",
      },
      {
        slug: "expat/tax-legal",
        label: "Tax & Legal",
        labelTh: "ภาษี กฎหมาย",
        description: "Tax and legal updates for residents",
        category: "Expat News",
        subcategory: "Tax & Legal",
        priority: "high",
        monetization: "Legal Ads",
        href: "/news/expat/tax-legal",
      },
      {
        slug: "nightlife/walking-street",
        label: "Walking Street",
        labelTh: "Walking Street",
        description: "Walking Street news and nightlife updates",
        category: "Nightlife",
        subcategory: "Walking Street",
        priority: "high",
        monetization: "Ads",
        href: "/news/nightlife/walking-street",
      },
      {
        slug: "nightlife/clubs-bars",
        label: "Clubs & Bars",
        labelTh: "คลับ บาร์",
        description: "Nightlife updates from clubs and bars",
        category: "Nightlife",
        subcategory: "Clubs & Bars",
        priority: "high",
        monetization: "Ads",
        href: "/news/nightlife/clubs-bars",
      },
      {
        slug: "sports/muay-thai",
        label: "Muay Thai",
        labelTh: "มวย",
        description: "Muay Thai events and news in Pattaya",
        category: "Sports",
        subcategory: "Muay Thai",
        priority: "medium",
        monetization: "Sponsorship",
        href: "/news/sports/muay-thai",
      },
      {
        slug: "sports/golf",
        label: "Golf",
        labelTh: "กอล์ฟ",
        description: "Golf news and tournaments in the region",
        category: "Sports",
        subcategory: "Golf",
        priority: "medium",
        monetization: "Sponsorship",
        href: "/news/sports/golf",
      },
      {
        slug: "international/global",
        label: "Pattaya in World News",
        labelTh: "ข่าวพัทยาจากต่างประเทศ",
        description: "International media coverage of Pattaya",
        category: "International",
        subcategory: "Global Media",
        priority: "medium",
        monetization: "Ads",
        features: "Multi-language",
        href: "/news/international/global",
      },
    ],
  },
  {
    id: "living",
    label: "Living",
    labelTh: "การอยู่อาศัย",
    description: "Expat guides, housing, healthcare, and daily life in Pattaya",
    href: "/living",
    items: [
      {
        slug: "visa/retirement",
        label: "Retirement Visa",
        labelTh: "วีซ่าเกษียณ",
        description: "Guide to retirement visa requirements and process",
        category: "Visa & Immigration",
        subcategory: "Retirement Visa",
        priority: "very-high",
        monetization: "Visa Service",
        features: "SEO",
        href: "/living/visa/retirement",
      },
      {
        slug: "visa/thailand-elite",
        label: "Thailand Elite",
        labelTh: "Elite Visa",
        description: "Thailand Elite visa program overview",
        category: "Visa & Immigration",
        subcategory: "Thailand Elite",
        priority: "high",
        monetization: "Affiliate",
        href: "/living/visa/thailand-elite",
      },
      {
        slug: "visa/work-permit",
        label: "Work Permit",
        labelTh: "ใบอนุญาตทำงาน",
        description: "Work permit application and requirements",
        category: "Visa & Immigration",
        subcategory: "Work Permit",
        priority: "high",
        monetization: "Legal Service",
        href: "/living/visa/work-permit",
      },
      {
        slug: "visa/90-day-report",
        label: "90-Day Report",
        labelTh: "รายงานตัว 90 วัน",
        description: "How to complete your 90-day immigration reporting",
        category: "Visa & Immigration",
        subcategory: "90-Day Report",
        priority: "high",
        href: "/living/visa/90-day-report",
      },
      {
        slug: "housing/condo-buying",
        label: "Condo Buying",
        labelTh: "ซื้อคอนโด",
        description: "Guide to buying a condo in Pattaya",
        category: "Housing",
        subcategory: "Condo Buying",
        priority: "very-high",
        monetization: "Property Ads",
        href: "/living/housing/condo-buying",
      },
      {
        slug: "housing/rentals",
        label: "Rentals",
        labelTh: "เช่าบ้าน",
        description: "Finding and renting property in Pattaya",
        category: "Housing",
        subcategory: "Rentals",
        priority: "high",
        monetization: "Property Ads",
        href: "/living/housing/rentals",
      },
      {
        slug: "housing/ownership",
        label: "Leasehold vs Freehold",
        labelTh: "สิทธิการถือครอง",
        description: "Understanding property ownership options in Thailand",
        category: "Housing",
        subcategory: "Ownership",
        priority: "high",
        monetization: "Legal Ads",
        href: "/living/housing/ownership",
      },
      {
        slug: "cost-of-living/utilities",
        label: "Utilities Cost",
        labelTh: "ค่าไฟ น้ำ Internet",
        description: "Electricity, water, and internet costs in Pattaya",
        category: "Cost of Living",
        subcategory: "Utilities",
        priority: "high",
        monetization: "Affiliate",
        href: "/living/cost-of-living/utilities",
      },
      {
        slug: "cost-of-living/food",
        label: "Daily Cost",
        labelTh: "ค่ากินอยู่",
        description: "Food and daily living expenses in Pattaya",
        category: "Cost of Living",
        subcategory: "Food Costs",
        priority: "medium",
        href: "/living/cost-of-living/food",
      },
      {
        slug: "healthcare/hospitals",
        label: "Hospitals",
        labelTh: "โรงพยาบาล",
        description: "Hospitals and medical facilities in Pattaya",
        category: "Healthcare",
        subcategory: "Hospitals",
        priority: "high",
        monetization: "Medical Ads",
        href: "/living/healthcare/hospitals",
      },
      {
        slug: "healthcare/insurance",
        label: "Health Insurance",
        labelTh: "ประกันสุขภาพ",
        description: "Health insurance options for expats and residents",
        category: "Healthcare",
        subcategory: "Insurance",
        priority: "high",
        monetization: "Affiliate",
        href: "/living/healthcare/insurance",
      },
      {
        slug: "transportation/songthaew",
        label: "Songthaew",
        labelTh: "รถสองแถว",
        description: "Using local songthaew transport in Pattaya",
        category: "Transportation",
        subcategory: "Songthaew",
        priority: "high",
        monetization: "Ads",
        href: "/living/transportation/songthaew",
      },
      {
        slug: "transportation/ride-apps",
        label: "Grab & Bolt",
        labelTh: "App เดินทาง",
        description: "Ride-hailing apps available in Pattaya",
        category: "Transportation",
        subcategory: "Ride Apps",
        priority: "medium",
        monetization: "Affiliate",
        href: "/living/transportation/ride-apps",
      },
      {
        slug: "transportation/driving",
        label: "Driving in Thailand",
        labelTh: "ขับรถในไทย",
        description: "Driving licenses, rules, and tips for Pattaya",
        category: "Transportation",
        subcategory: "Driving",
        priority: "high",
        monetization: "Insurance Ads",
        href: "/living/transportation/driving",
      },
      {
        slug: "culture/etiquette",
        label: "Do & Don't",
        labelTh: "สิ่งควรทำ/ไม่ควรทำ",
        description: "Cultural etiquette guide for living in Thailand",
        category: "Culture & Etiquette",
        subcategory: "Etiquette",
        priority: "very-high",
        features: "SEO",
        href: "/living/culture/etiquette",
      },
      {
        slug: "culture/thai-culture",
        label: "Thai Culture",
        labelTh: "วัฒนธรรมไทย",
        description: "Understanding Thai culture as a resident",
        category: "Culture & Etiquette",
        subcategory: "Thai Culture",
        priority: "high",
        features: "SEO",
        href: "/living/culture/thai-culture",
      },
      {
        slug: "safety/scam-alerts",
        label: "Scam Alerts",
        labelTh: "การโกงนักท่องเที่ยว",
        description: "Common scams and how to avoid them in Pattaya",
        category: "Safety",
        subcategory: "Scam Alerts",
        priority: "very-high",
        features: "SEO",
        href: "/living/safety/scam-alerts",
      },
      {
        slug: "safety/emergency-guide",
        label: "Emergency Guide",
        labelTh: "วิธีรับมือเหตุฉุกเฉิน",
        description: "How to handle emergencies in Pattaya",
        category: "Safety",
        subcategory: "Emergency Guide",
        priority: "high",
        href: "/living/safety/emergency-guide",
      },
    ],
  },
  {
    id: "explore",
    label: "Explore",
    labelTh: "ท่องเที่ยว",
    description: "Beaches, restaurants, activities, and hidden gems",
    href: "/explore",
    items: [
      {
        slug: "beaches",
        label: "Main Beaches",
        labelTh: "ชายหาดหลัก",
        description: "Pattaya's main beaches and what to expect",
        category: "Beaches",
        subcategory: "Main Beaches",
        priority: "high",
        monetization: "Affiliate",
        href: "/explore/beaches",
      },
      {
        slug: "islands/koh-larn",
        label: "Koh Larn",
        labelTh: "เกาะล้าน",
        description: "Island day trips and activities at Koh Larn",
        category: "Islands",
        subcategory: "Koh Larn",
        priority: "high",
        monetization: "Tours",
        href: "/explore/islands/koh-larn",
      },
      {
        slug: "restaurants/fine-dining",
        label: "Fine Dining",
        labelTh: "ร้านอาหารหรู",
        description: "Luxury dining experiences in Pattaya",
        category: "Restaurants",
        subcategory: "Fine Dining",
        priority: "high",
        monetization: "Sponsored",
        href: "/explore/restaurants/fine-dining",
      },
      {
        slug: "restaurants/street-food",
        label: "Street Food",
        labelTh: "อาหารท้องถิ่น",
        description: "Best local and street food in Pattaya",
        category: "Restaurants",
        subcategory: "Street Food",
        priority: "high",
        monetization: "Sponsored",
        href: marketPagePaths.streetFoodPage,
      },
      {
        slug: "cafes",
        label: "Specialty Coffee",
        labelTh: "คาเฟ่",
        description: "Cafes and specialty coffee spots",
        category: "Cafes",
        subcategory: "Specialty Coffee",
        priority: "medium",
        monetization: "Sponsored",
        href: "/explore/cafes",
      },
      {
        slug: "shopping/malls",
        label: "Shopping Malls",
        labelTh: "ห้าง",
        description: "Malls and shopping centers in Pattaya",
        category: "Shopping",
        subcategory: "Shopping Malls",
        priority: "medium",
        monetization: "Affiliate",
        href: "/explore/shopping/malls",
      },
      {
        slug: "shopping/markets",
        label: "Local Markets",
        labelTh: "ตลาด",
        description: "Markets and local shopping experiences",
        category: "Shopping",
        subcategory: "Local Markets",
        priority: "high",
        monetization: "Ads",
        href: marketPagePaths.page,
      },
      {
        slug: "family-activities",
        label: "Family Activities",
        labelTh: "กิจกรรมครอบครัว",
        description: "Kid-friendly activities and family outings",
        category: "Family Activities",
        subcategory: "Kids Activities",
        priority: "medium",
        monetization: "Affiliate",
        href: "/explore/family-activities",
      },
      {
        slug: "luxury/yacht",
        label: "Yacht & Marina",
        labelTh: "เรือยอร์ช",
        description: "Yacht charters and marina experiences",
        category: "Luxury",
        subcategory: "Yacht & Marina",
        priority: "medium",
        monetization: "Luxury Ads",
        href: "/explore/luxury/yacht",
      },
      {
        slug: "hidden-gems",
        label: "Hidden Gems",
        labelTh: "จุดลับ",
        description: "Secret spots off the beaten path",
        category: "Hidden Gems",
        subcategory: "Secret Spots",
        priority: "medium",
        features: "SEO",
        href: "/explore/hidden-gems",
      },
      {
        slug: "wellness",
        label: "Spa & Massage",
        labelTh: "สปา นวด",
        description: "Wellness, spa, and massage recommendations",
        category: "Wellness",
        subcategory: "Spa & Massage",
        priority: "high",
        monetization: "Affiliate",
        href: "/explore/wellness",
      },
    ],
  },
  {
    id: "business",
    label: "Business",
    labelTh: "ธุรกิจ",
    description: "Company setup, investment guides, and B2B networking",
    href: "/business",
    items: [
      {
        slug: "company-setup/thai-company",
        label: "Company Registration",
        labelTh: "เปิดบริษัท",
        description: "How to register a Thai company in Pattaya",
        category: "Company Setup",
        subcategory: "Thai Company",
        priority: "high",
        monetization: "Legal Ads",
        href: "/business/company-setup/thai-company",
      },
      {
        slug: "company-setup/boi",
        label: "BOI Promotion",
        labelTh: "สิทธิ BOI",
        description: "Board of Investment incentives and application",
        category: "Company Setup",
        subcategory: "BOI Promotion",
        priority: "medium",
        monetization: "Consulting",
        href: "/business/company-setup/boi",
      },
      {
        slug: "guide/restaurant",
        label: "F&B Business",
        labelTh: "เปิดร้านอาหาร",
        description: "Starting a restaurant business in Pattaya",
        category: "Business Guide",
        subcategory: "Restaurant Business",
        priority: "high",
        monetization: "Consulting",
        href: "/business/guide/restaurant",
      },
      {
        slug: "guide/bar",
        label: "Bar Business",
        labelTh: "เปิดบาร์",
        description: "Opening a bar or nightlife venue",
        category: "Business Guide",
        subcategory: "Bar Business",
        priority: "high",
        monetization: "Consulting",
        href: "/business/guide/bar",
      },
      {
        slug: "guide/hotel",
        label: "Hotel Business",
        labelTh: "โรงแรม",
        description: "Hospitality and hotel investment guide",
        category: "Business Guide",
        subcategory: "Hotel Business",
        priority: "high",
        monetization: "Consulting",
        href: "/business/guide/hotel",
      },
      {
        slug: "investment/real-estate",
        label: "Property Investment",
        labelTh: "ลงทุนอสังหา",
        description: "Real estate investment opportunities in Pattaya",
        category: "Investment",
        subcategory: "Property Investment",
        priority: "high",
        monetization: "Property Ads",
        href: "/business/investment/real-estate",
      },
      {
        slug: "investment/economy",
        label: "Pattaya Economy",
        labelTh: "เศรษฐกิจพัทยา",
        description: "Economic overview and trends in Pattaya",
        category: "Investment",
        subcategory: "Economy",
        priority: "medium",
        monetization: "Sponsorship",
        href: "/business/investment/economy",
      },
      {
        slug: "networking/events",
        label: "Business Networking",
        labelTh: "Networking ธุรกิจ",
        description: "Business events and networking opportunities",
        category: "Networking",
        subcategory: "Business Events",
        priority: "medium",
        monetization: "Event Ads",
        href: "/business/networking/events",
      },
    ],
  },
];

export const homeWidgets: HomeWidget[] = [
  {
    id: "top-stories",
    label: "Top Stories",
    labelTh: "ข่าวเด่นประจำวัน",
    description: "Featured news with AI summaries",
    priority: "very-high",
    monetization: "Ads",
    features: "AI Summary + Multi-language",
  },
  {
    id: "breaking-news",
    label: "Breaking News",
    labelTh: "ข่าวด่วน",
    description: "Urgent updates from around Pattaya",
    priority: "very-high",
    monetization: "Ads",
    features: "Real-time",
  },
  {
    id: "events-today",
    label: "Events Today",
    labelTh: "งานวันนี้",
    description: "Daily events calendar",
    href: "/events",
    priority: "high",
    monetization: "Event Ads",
    features: "Calendar",
  },
  {
    id: "weather",
    label: "Weather",
    labelTh: "สภาพอากาศ",
    description: "Current weather conditions",
    href: "/utilities/weather",
    priority: "medium",
    features: "API Widget",
  },
  {
    id: "traffic-transport",
    label: "Traffic & Transport",
    labelTh: "การเดินทาง",
    description: "Road conditions, transport, and airport info",
    href: "/utilities/transport",
    priority: "medium",
    features: "Live Update",
  },
  {
    id: "trending-forum",
    label: "Trending Forum",
    labelTh: "กระทู้ยอดนิยม",
    description: "Popular community discussions",
    href: "/forum/trending",
    priority: "high",
    monetization: "Premium",
    features: "Community Driven",
  },
  {
    id: "pattaya-guide",
    label: "Pattaya Guide",
    labelTh: "คู่มือเมือง",
    description: "Essential city guide for visitors and residents",
    href: "/guide",
    priority: "high",
    features: "SEO",
  },
  {
    id: "emergency-contacts",
    label: "Emergency Contacts",
    labelTh: "เบอร์ฉุกเฉิน",
    description: "Important emergency phone numbers",
    href: "/emergency",
    priority: "high",
  },
  {
    id: "currency-rates",
    label: "Currency Rates",
    labelTh: "ค่าเงิน",
    description: "Live exchange rates",
    href: "/utilities/currency",
    priority: "medium",
    monetization: "Affiliate",
    features: "API",
  },
  {
    id: "featured-businesses",
    label: "Featured Businesses",
    labelTh: "ธุรกิจแนะนำ",
    description: "Sponsored business listings",
    href: "/directory/featured",
    priority: "high",
    monetization: "Featured Listing",
  },
];

export const mainNavItems = [
  { label: "Home", labelTh: "หน้าแรก", href: "/" },
  ...mainSections.map(({ label, labelTh, href }) => ({ label, labelTh, href })),
];

export function getSectionById(id: string): MainSection | undefined {
  return mainSections.find((section) => section.id === id);
}

export function getNavItemBySlug(
  sectionId: string,
  slugParts: string[],
): NavItem | undefined {
  const section = getSectionById(sectionId);
  if (!section) return undefined;

  const slug = slugParts.join("/");
  return section.items.find((item) => item.slug === slug);
}

export function groupItemsByCategory(items: NavItem[]): Record<string, NavItem[]> {
  return items.reduce<Record<string, NavItem[]>>((groups, item) => {
    const key = item.category;
    if (!groups[key]) groups[key] = [];
    groups[key].push(item);
    return groups;
  }, {});
}

export function getTotalCategoryCount(): number {
  return mainSections.reduce((total, section) => total + section.items.length, 0);
}
