/** Stable URLs for /explore/shopping/markets — use for cross-page links */
export const marketPagePaths = {
  page: "/explore/shopping/markets",
  schedule: "/explore/shopping/markets#market-schedule",
  map: "/explore/shopping/markets#markets-map",
  hiddenSection: "/explore/shopping/markets#hidden-markets",
  thepprasit: "/explore/shopping/markets#market-thepprasit",
  pattayaPark: "/explore/shopping/markets#market-pattaya-park",
  buakhao: "/explore/shopping/markets#market-buakhao",
  oldNaklua: "/explore/shopping/markets#market-old-naklua",
  jomtienCooked: "/explore/shopping/markets#market-jomtien-cooked",
  pattayaKlang: "/explore/shopping/markets#market-pattaya-klang",
  angSila: "/explore/shopping/markets#market-ang-sila",
  klongtom: "/explore/shopping/markets#market-klongtom",
  treeMarket: "/explore/shopping/markets#market-tree-market",
  floating: "/explore/shopping/markets#market-floating",
  nightBazaar: "/explore/shopping/markets#market-night-bazaar",
  madeInThailand: "/explore/shopping/markets#market-made-in-thailand",
  hiddenWatChaiMongkhon: "/explore/shopping/markets#hidden-market-wat-chai-mongkhon",
  hiddenLanPho: "/explore/shopping/markets#hidden-market-lan-pho-naklua",
  hiddenNoenPlubWan: "/explore/shopping/markets#hidden-market-noen-plub-wan",
  hiddenWatTham: "/explore/shopping/markets#hidden-market-wat-tham-samakkee",
  hiddenNakluaOldTown: "/explore/shopping/markets#hidden-market-naklua-old-town",
  streetFoodThepprasit: "/explore/restaurants/street-food#market-thepprasit",
} as const;
